name: My Workflow    #워크플로우 이름

on: [push, pull_request]  #트리거 이벤트

jobs:    #직접 정의
  build:
    runs-on: ubuntu-latest    # 러너 환경
    steps:    # 단계
      - uses: actions/checkout@v3
      - run: echo "Hello World"
